name: ang2huntdart
description: A sample web application with dart force
dependencies:
  force:
    git:
      url: git://github.com/ForceUniverse/dart-force.git
  bigcargo:
       git: git://github.com/ForceUniverse/bigcargo
  cargo: any
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
